name: Checks Code

on:
  push:
    branches:
      - main
      - dev

jobs:
  testing-and-linting:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout Git
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version  # Verify that docker-compose is installed

      - name: Testing
        run: docker-compose run --rm app /bin/sh -c "python manage.py wait_for_db && python3 manage.py test"

      - name: Linting
        run: docker-compose run --rm app /bin/sh -c "flake8"
